In [1]:
from sympy import init_printing, Matrix, symbols, sqrt, Rational
from numpy import matrix, transpose, sqrt, eye
from numpy.linalg import pinv, inv, det, svd, norm, eig
from scipy.linalg import pinv as pinv2
from warnings import filterwarnings

In [2]:
init_printing(use_latex="mathjax")
filterwarnings("ignore")

# Review of select topics

## Quick facts

+ Eigenvalues
    + There are shortcuts that we can sometimes employ to calculate them
+ In symmetric matrices A = A<sup>T</sup>
    + Their eigenvalues are always real
    + There are always enough eigenvectors and we can choose them to be orthogonal
    + They van be diagonalized and factorized as Q&Lambda'Q<sup>T</sup>
+ Similar matrices are any square matrices that are related by A = M<sup>-1</sup>BM
    + They have the same eigenvalues (not eigenvectors)
    + As one grows / decays so does the other A<sup>k</sup> = M<sup>-1</sup>B<sup>k</sup>M

## Exercise problems

### Differential equation matrix

+ Consider the following and solve for a general solution and solve for *e*<sup>At</sup>
$$ \frac{du}{dt}={A}{u}=\begin{bmatrix}0&-1&0\\1&0&-1\\0&1&0\end{bmatrix}{u} $$

+ There are no initial condition, so we need the general solutions
    + They will be in the form
    $$ u\left(t\right)={c}_{1}{e}^{{\lambda}_{1}{t}}{x}_{1}+{c}_{2}{e}^{{\lambda}_{2}{t}}{x}_{2}+{c}_{3}{e}^{{\lambda}_{3}{t}}{x}_{3} $$

In [3]:
A = Matrix([[0, -1, 0], [1, 0, -1], [0, 1, 0]])
A, A.det()

⎛⎡0  -1  0 ⎤   ⎞
⎜⎢         ⎥   ⎟
⎜⎢1  0   -1⎥, 0⎟
⎜⎢         ⎥   ⎟
⎝⎣0  1   0 ⎦   ⎠

+ It is clearly singular (dependent rows and columns)

In [4]:
A.transpose()

⎡0   1   0⎤
⎢         ⎥
⎢-1  0   1⎥
⎢         ⎥
⎣0   -1  0⎦

+ It is skew-symmetric and therefor eigenvalues are purely complex numbers (including 0*i*)

In [5]:
A.eigenvals()

{0: 1, -√2⋅ⅈ: 1, √2⋅ⅈ: 1}

+ The solution is thus as follows
$$ u\left(t\right)={c}_{1}{x}_{1}+{c}_{2}{e}^{{\sqrt{2}i}{t}}{x}_{2}+{c}_{3}{e}^{{-\sqrt{2}i}{t}}{x}_{3} $$
+ The solution moves around the unit circle (doesn't grow / decay)
+ It returns to the same value (it's periodic) after a certain time *t*
$$ \sqrt{2}{i}{T}=2{\pi}{i};\quad{e}^{0}=1 \\ \sqrt{2}{T}=2{\pi} \\ {T}={\pi}\sqrt{2} $$

+ Finding *u*(*t*) allows the following
$$ u\left(t\right)={e}^{At}u\left(0\right) $$

+ If A is diagonalizable (A = S&Lambda;S<sup>-1</sup>) then we have the following
$$ {e}^{At}=S{e}^{\Lambda{t}}{S}^{-1} \\ { e }^{ \Lambda t }=\begin{bmatrix} { e }^{ { \lambda  }_{ 1 }t } & 0 & 0 \\ 0 & \ddots  & 0 \\ 0 & 0 & { e }^{ { \lambda  }_{ n }t } \end{bmatrix} $$

### Orthogonal eigenvalues

+ Which matrices have orthogonal eigenvectors?

+ The following
    + Symmetric matrices
    + When A<sup>T</sup> = -A (skew-symmetric)
    + Orthogonal matrices
    + In general these are all when AA<sup>T</sup>=A<sup>T</sup>A

### Definitions

+ Given the following
$$ { \lambda  }_{ 1 }=0;\quad { \lambda  }_{ 2 }=c;\quad { \lambda  }_{ 3 }=2\\ { x }_{ 1 }=\begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix},\quad { x }_{ 2 }=\begin{bmatrix} 1 \\ -1 \\ 0 \end{bmatrix},\quad { x }_{ 3 }=\begin{bmatrix} 1 \\ 1 \\ 2 \end{bmatrix} $$

+ Is the matrix A diagonalizable and of so for which value(s) of *c*?
    + So we need enough enough eigenvectors and they should be independent
    + They are indeed
    + More so they are orthogonal
    + So, for all *c* the matrix is diagonalizable

+ Is A symmetric and if so, for which value(s) of *s*?
    + The eigenvalues all have to be real values
    + Thus all real values for *c*

+ Is A positive definite and if so, for which values of *c*?
    + This is a sub-case of symmetric matrices
    + There are a lot of tests for positive definite matrices
    + One of the eigenvalues are zero, so it can, at best, be semi-definite, for *c* &ge; 0

+ Is this a Markov matrix and if so, for which values of *c*?
    + One of the eigenvalues must be 1 and the others must be smaller
    + So, no

+ Could &frac12;A be a projection matrix?
    + They are symmetric and eigenvalues must be real
    + Any projection matrix eigenvalues must be 0 and 1
    $$ P=\frac{A}{2} \\ {P}^{2}=P \\ \therefore {\lambda}^{2}=\lambda \\ \therefore \lambda = 0; \quad \lambda = 1 $$
    + Thus *c* = 0 or *c* = 2 will work (for &frac12;A we will have &frac12;&lambda;)

### Singular value decomposition

+ In SVD we have the following
$$ A=U\Sigma {V}^{T} $$
+ Where U and V are orthogonal matrices and &Sigma; a diagonal matrix

+ Every matrix has a SVD
$$ {A}^{T}A=\left( V {\Sigma}^{T} {U}^{T} \right) \left( U {\Sigma} {V}^{T} \right) \\ {A}^{T} A = V \left( {\Sigma}^{T} {\Sigma} \right) {V}^{T} $$
+ V is the eigenvector matrix for A<sup>T</sup>
+ &Sigma: has along its main diagonal the square roots of the eigenvalues
+ U is similarly calculated as the eigenvector matrix of AA<sup>T</sup>
+ There is always, though, as sign issue when choosing V and U
    + For whichever signs are chosen for V, this forces the signs for U which can be checked against the following
    $$ A{v}_{i} = {\sigma}_{i} {u}_{i} \\ AV = \Sigma U $$
+ &Sigma; can tell us a lot about A
    + All values must be &ge; 0
    + If it contains a 0 along the main diagonal, A is singular

### Symmetric AND orthogonal matrices (matrices that are both)
+ A = A<sup>T</sup> = A<sup>-1</sup>

+ What can be said about the eigenvalues of these?
    + Symmetric matrices have real eigenvalues and the orthogonal matrix eigenvalues must have length 1; ||&lambda;|| = 1

+ Is A sure to be positive definite?
    + No, as &lambda; can be -1

+ Does it have repeated eigenvalues?
    + Yes (if *n* &ge; 2, some eigenvalues must be repeated)

+ Is it diagonalizable?
    + Most definitely

+ Is it non-singular
    + Yes (no zero eigenvalues)

+ Prove that the following is a projection matrix
$$ \frac{1}{2} \left( A+I \right) $$ 
    + Squaring it should result in the same
    $$ \frac{1}{4} \left( {A}^{2} + 2A + I \right) $$
    + This begs the question, what is A<sup>2</sup>?
    + Well, if A equals its inverse, A<sup>2</sup> = I
    + As an aside the eigenvalues of A + I will be twice the eigenvalues of A

## Example problems

### Example problem 1

+ Find the eigenvalues and eigenvectors of the following
    + 1: The projection matrix P
    $$ {P} = \frac{{a}{a}^{T}}{{a}^{T}{a}}; \quad a= \begin{bmatrix}3\\4\end{bmatrix} $$
    + 2: The matrix Q
    $$ Q = \begin{bmatrix}0.6&-0.8\\0.8&0.6\end{bmatrix} $$
    + 3: The matrix R
    $$ R = 2P - I $$

#### Solution

+ 1:

In [6]:
a = matrix([[3], [4]])  # Not using sympy
P = (a * transpose(a)) / (transpose(a) * a)
P

matrix([[0.36, 0.48],
        [0.48, 0.64]])

+ The eigenvalues of a projection matrix are either 0 or 1

In [7]:
eig(P)  # eig() gives the eigenvalues and eigenvector matrix

EigResult(eigenvalues=array([0., 1.]), eigenvectors=matrix([[-0.8, -0.6],
        [ 0.6, -0.8]]))

+ 2:

In [8]:
Q = matrix([[0.6, -0.8], [0.8, 0.6]])
Q

matrix([[ 0.6, -0.8],
        [ 0.8,  0.6]])

+ Note that Q is a projection matrix

In [9]:
eig(Q)  # eigenvalues come in complex conjugate pairs

EigResult(eigenvalues=array([0.6+0.8j, 0.6-0.8j]), eigenvectors=matrix([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

+ 3:

+ R will have the same eigenvectors, but (shifted) eigenvalues

In [10]:
R = 2 * P - eye(2)
R

matrix([[-0.28,  0.96],
        [ 0.96,  0.28]])

In [11]:
eig(R)

EigResult(eigenvalues=array([-1.,  1.]), eigenvectors=matrix([[-0.8, -0.6],
        [ 0.6, -0.8]]))

+ The eigenvalues of P was 0 and 1
    + 2 &times; 0 - 1 = -1
    + 2 &times; 1 - 1 = 1